
#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION (1U)
#define PORT_PBCFG_SW_MINOR_VERSION (0U)
#define PORT_PBCFG_SW_PATCH_VERSION (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION (3U)

/* AUTOSAR Version checking between Dio_PBcfg.c and Dio.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 || (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
  || (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
#error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Dio_PBcfg.c and Dio.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION) || (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION) || (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
#error "The SW version of PBcfg.c does not match the expected version"
#endif


/* PB structure used with Dio_Init API */
const Port_ConfigType Port_Configuration = {
    PORT_A_NUM, PORT_PIN_0_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT A PIN 0 configuration*/
    PORT_A_NUM, PORT_PIN_1_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT A PIN 1 configuration*/
    PORT_A_NUM, PORT_PIN_2_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT A PIN 2 configuration*/
    PORT_A_NUM, PORT_PIN_3_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT A PIN 3 configuration*/
    PORT_A_NUM, PORT_PIN_4_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT A PIN 4 configuration*/
    PORT_A_NUM, PORT_PIN_5_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT A PIN 5 configuration*/
    PORT_A_NUM, PORT_PIN_6_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT A PIN 6 configuration*/
    PORT_A_NUM, PORT_PIN_7_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT A PIN 7 configuration*/

    PORT_B_NUM, PORT_PIN_0_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT B PIN 0 configuration*/
    PORT_B_NUM, PORT_PIN_1_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT B PIN 1 configuration*/
    PORT_B_NUM, PORT_PIN_2_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT B PIN 2 configuration*/
    PORT_B_NUM, PORT_PIN_3_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT B PIN 3 configuration*/
    PORT_B_NUM, PORT_PIN_4_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT B PIN 4 configuration*/
    PORT_B_NUM, PORT_PIN_5_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT B PIN 5 configuration*/
    PORT_B_NUM, PORT_PIN_6_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT B PIN 6 configuration*/
    PORT_B_NUM, PORT_PIN_7_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT B PIN 7 configuration*/

    PORT_C_NUM, PORT_PIN_0_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT C PIN 0 configuration*/
    PORT_C_NUM, PORT_PIN_1_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT C PIN 1 configuration*/
    PORT_C_NUM, PORT_PIN_2_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT C PIN 2 configuration*/
    PORT_C_NUM, PORT_PIN_3_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT C PIN 3 configuration*/
    PORT_C_NUM, PORT_PIN_4_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT C PIN 4 configuration*/
    PORT_C_NUM, PORT_PIN_5_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT C PIN 5 configuration*/
    PORT_C_NUM, PORT_PIN_6_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT C PIN 6 configuration*/
    PORT_C_NUM, PORT_PIN_7_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT C PIN 7 configuration*/

    PORT_D_NUM, PORT_PIN_0_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT D PIN 0 configuration*/
    PORT_D_NUM, PORT_PIN_1_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT D PIN 1 configuration*/
    PORT_D_NUM, PORT_PIN_2_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT D PIN 2 configuration*/
    PORT_D_NUM, PORT_PIN_3_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT D PIN 3 configuration*/
    PORT_D_NUM, PORT_PIN_4_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT D PIN 4 configuration*/
    PORT_D_NUM, PORT_PIN_5_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT D PIN 5 configuration*/
    PORT_D_NUM, PORT_PIN_6_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT D PIN 6 configuration*/
    PORT_D_NUM, PORT_PIN_7_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT D PIN 7 configuration*/

    PORT_E_NUM, PORT_PIN_0_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT E PIN 0 configuration*/
    PORT_E_NUM, PORT_PIN_1_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT E PIN 1 configuration*/
    PORT_E_NUM, PORT_PIN_2_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT E PIN 2 configuration*/
    PORT_E_NUM, PORT_PIN_3_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT E PIN 3 configuration*/
    PORT_E_NUM, PORT_PIN_4_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT E PIN 4 configuration*/
    PORT_E_NUM, PORT_PIN_5_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON, /*PORT E PIN 5 configuration*/

    PORT_F_NUM, PORT_PIN_0_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON,    /*PORT F PIN 0 configuration (SW0)*/
    PORT_F_NUM, PORT_PIN_1_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON,    /*PORT F PIN 1 configuration (LED1)*/
    PORT_F_NUM, PORT_PIN_2_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON,    /*PORT F PIN 2 configuration (LED2)*/
    PORT_F_NUM, PORT_PIN_3_NUM, PORT_PIN_OUT, OFF, PORT_PIN_MODE_GPIO, STD_LOW, STD_ON, STD_ON,    /*PORT F PIN 3 configuration (LED3)*/
    PORT_F_NUM, PORT_PIN_4_NUM, PORT_PIN_IN, PULL_UP, PORT_PIN_MODE_GPIO, STD_HIGH, STD_ON, STD_ON /*PORT F PIN 4 configuration (SW1)*/

};